sonar.projectKey=katsuki2000_SmartTax
sonar.organization=railala-mahalahatse
sonar.sources=.
sonar.exclusions=node_modules/**, coverage/**, **/*.test.js, eslint.config.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info